export const SITE = {
  website: "https://essalemy.com/",
  author: "Mohamed Essalemy",
  profile: "https://www.linkedin.com/in/essalemy/",
  desc: "Documenting how I automate business processes, build practical tools, and solve real operational problems — from Excel and Power Platform to web apps and APIs.",
  title: "Essalemy",
  ogImage: undefined,
  lightAndDarkMode: true,
  postPerIndex: 5,
  postPerPage: 5,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Suggest Changes",
    url: "https://github.com/MedEssalemy/personal-blog/edit/main/src/data/blog/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Europe/Paris",
} as const;
